name: OpenEVT
version: "1.0.0"
slug: openevt
description: |
  The OpenEVT app connects to a compatible Envertech inverter and exposes its data to Home Assistant.
arch:
  - amd64
  - aarch64
ports:
  9090/tcp: 9090
options:
  address: ""
  serial_number: ""
  web_listen_address: ":9090"
  telemetry_path: "/metrics"
  disable_exporter_metrics: false
  poll_interval: "5s"
  reconnect_interval: "1m"
  log_level: INFO
schema:
  address: str
  serial_number: str
  web_listen_address: str
  telemetry_path: str
  disable_exporter_metrics: bool
  poll_interval: str
  reconnect_interval: str
  log_level: str
init: false
