name: OpenEVT
version: "1.0.0"
slug: openevt
description: |
  The OpenEVT app connects to a compatible Envertech inverter and exposes its data to Home Assistant.
arch:
  - amd64
  - aarch64
ports:
  9090/tcp: 9090
options:
  address: ""
  serial_number: ""
schema:
  address: str
  serial_number: str
init: false
